### ISSUE TITLE
Stub out automated feedback API

### ISSUE THREAD

**Issue by aolney** [aolney/mofacts-automated-authoring#17]
Inputs:

- Item presented to student (string)
- Correct answer for that item (string)
- Answer given by student (string)

Output:

- A string consisting of the feedback to deliver to the student

**Comment by aolney** [comment]
Is this OK for you guys?

**Comment by andrewtackett** [comment]
I think this is the thread you were referring to on Wednesday.

That's fine by me. Note that the item presented to the student is not the full sentence but the sentence with underscores instead of the correct answer.  Also combined with the new syllable unit this will contain some partial words as part of the correct answer/item presented. (I.E. Item presented: "I like tur___", correct answer: "tles"). I assume it would be easier for you to know exactly what is/isn't part of the answer so I could instead pass the original item ("I like ____") and original answer ("turtles") instead or both.  Also note we count either the missing part of a subword cloze or the full cloze as correct.

**Comment by aolney** [comment]
Sounds good. If you could pass me the complete word, that would seem to be a more stable API since we don't know what other kinds of hints will be given in the future.

**Comment by andrewtackett** [comment]
Ok, just to be explicit, I'm going to give you:

Original Item
Original Answer
Current Correct Answer (which may be identical to original answer in the case of no hints or a subset of original answer if given hints, in the case that it is not identical either original or current answer are accepted as correct)
Student Submitted Answer

And you give me:

Feedback string to display to the user

I include current correct answer because there might be some situation where for instance a substring of original answer is not correct (e.g. it's a distinct concept from what we actually want them to say, example: original answer: "upper epidermis" current correct answer: "epidermis" potentially incorrect student answer: "dermis")
